version: '3.8'
services:
  riroan-backend:
    build:
      dockerfile: Dockerfile
    ports:
      - '8988:8080'
    depends_on:
      - db
  riroan-db:
    image: 'mysql'
    volumes:
      - riroan-mysql-volume:/var/lib/mysql
    env_file:
      - ./mysql.env

volumes:
  riroan-mysql-volume:
