name: Frontend Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'riroan/**'
      - '.github/workflows/frontend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          port: ${{secrets.PORT}}
          script: |
            cd ~/riroan.com/riroan
            git pull
            yarn install
            yarn build
